insert into os_list values (NULL,"WINNT 5.1");
insert into os_list values (NULL,"WINNT 6.0");
insert into os_list values (NULL,"MacOSX Darwin 8.8.1");
insert into os_list values (NULL,"MacOSX Darwin 9.2.2");
insert into os_list values (NULL,"Ubuntu 7.10");
insert into os_list values (NULL,"CentOS release 5 (Final)");
insert into os_list values (NULL,"MacOSX 10.5.2");
insert into os_list values (NULL,"WINNT 5.2");
insert into os_list values (NULL,"Linux embed");

insert into branches values (NULL,"Firefox");
insert into branches values (NULL,"Firefox3.0");
insert into branches values (NULL,"Firefox3.1");
insert into branches values (NULL,"TraceMonkey");
insert into branches values (NULL,"Fennec");
insert into branches values (NULL,"MozillaTest");
insert into branches values (NULL,"Mobile");

-- osid,isthrottling,cpuspeed,name,isactive,dateadded
-- stage talos
insert into machines values (NULL,1,0,"1.63","qm-pxp-stage01",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.63","qm-pvista-stage01",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.63","qm-ptiger-stage01",1,unix_timestamp());
insert into machines values (NULL,4,0,"1.63","qm-pleopard-stage01",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.63","qm-pubuntu-stage01",1,unix_timestamp());
-- 1.9.0 talos
insert into machines values (NULL,1,0,"1.63","qm-mini-xp01",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.63","qm-mini-xp02",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.63","qm-mini-xp03",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.63","qm-mini-xp05",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.63","qm-mini-ubuntu01",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.63","qm-mini-ubuntu02",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.63","qm-mini-ubuntu03",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.63","qm-mini-ubuntu05",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.63","qm-pmac01",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.63","qm-pmac02",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.63","qm-pmac03",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.63","qm-pmac05",1,unix_timestamp());
insert into machines values (NULL,4,0,"1.83","qm-pleopard-trunk06",1,unix_timestamp());
insert into machines values (NULL,4,0,"1.83","qm-pleopard-trunk07",1,unix_timestamp());
insert into machines values (NULL,4,0,"1.83","qm-pleopard-trunk08",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.63","qm-mini-vista01",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.63","qm-mini-vista02",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.63","qm-mini-vista03",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.63","qm-mini-vista05",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-fast01",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-pmac-fast01",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.83","qm-plinux-fast01",1,unix_timestamp());
-- 1.9.1 talos
insert into machines values (NULL,5,0,"1.83","qm-plinux-talos01",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.83","qm-plinux-talos02",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.83","qm-plinux-talos03",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.83","qm-plinux-talos04",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-talos01",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-talos02",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-talos03",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-talos04",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-pmac-talos01",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-pmac-talos02",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-pmac-talos03",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-pmac-talos04",1,unix_timestamp());
insert into machines values (NULL,4,0,"1.83","qm-pleopard-talos01",1,unix_timestamp());
insert into machines values (NULL,4,0,"1.83","qm-pleopard-talos02",1,unix_timestamp());
insert into machines values (NULL,4,0,"1.83","qm-pleopard-talos03",1,unix_timestamp());
insert into machines values (NULL,4,0,"1.83","qm-pleopard-talos04",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.83","qm-pvista-talos01",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.83","qm-pvista-talos02",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.83","qm-pvista-talos03",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.83","qm-pvista-talos04",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-fast04",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-pmac-fast04",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.83","qm-plinux-fast04",1,unix_timestamp());
-- 1.9.2 talos
insert into machines values (NULL,5,0,"1.83","qm-plinux-trunk01",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.83","qm-plinux-trunk02",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.83","qm-plinux-trunk03",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.83","qm-plinux-trunk07",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-trunk01",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-trunk02",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-trunk03",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-trunk07",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-pmac-trunk01",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-pmac-trunk02",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-pmac-trunk03",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-pmac-trunk10",1,unix_timestamp());
insert into machines values (NULL,4,0,"1.83","qm-pleopard-trunk01",1,unix_timestamp());
insert into machines values (NULL,4,0,"1.83","qm-pleopard-trunk02",1,unix_timestamp());
insert into machines values (NULL,4,0,"1.83","qm-pleopard-trunk03",1,unix_timestamp());
insert into machines values (NULL,4,0,"1.83","qm-pleopard-trunk04",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.83","qm-pvista-trunk01",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.83","qm-pvista-trunk02",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.83","qm-pvista-trunk03",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.83","qm-pvista-trunk04",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-fast03",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-pmac-fast03",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.83","qm-plinux-fast03",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-jss01",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-jss02",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-jss03",1,unix_timestamp());
-- tracemonkey talos
insert into machines values (NULL,5,0,"1.83","qm-plinux-trunk04",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.83","qm-plinux-trunk05",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.83","qm-plinux-trunk06",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-trunk04",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-trunk05",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-trunk06",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-pmac-trunk07",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-pmac-trunk08",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-pmac-trunk09",1,unix_timestamp());
-- try talos
insert into machines values (NULL,5,0,"1.83","qm-ubuntu-try01",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-try01",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-ptiger-try01",1,unix_timestamp());
-- mobile talos
insert into machines values (NULL,9,0,NULL,"maemo-n810-01",1,unix_timestamp());
insert into machines values (NULL,9,0,NULL,"maemo-n810-02",1,unix_timestamp());
insert into machines values (NULL,9,0,NULL,"maemo-n810-03",1,unix_timestamp());
insert into machines values (NULL,9,0,NULL,"maemo-n810-04",1,unix_timestamp());
insert into machines values (NULL,9,0,NULL,"maemo-n810-05",1,unix_timestamp());
insert into machines values (NULL,9,0,NULL,"maemo-n810-06",1,unix_timestamp());
-- pool talos
insert into machines values (NULL,1,0,"1.83","qm-pxp-slave01",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-slave02",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-slave03",1,unix_timestamp());
insert into machines values (NULL,1,0,"1.83","qm-pxp-slave04",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.83","qm-pvista-slave01",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.83","qm-pvista-slave02",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.83","qm-pvista-slave03",1,unix_timestamp());
insert into machines values (NULL,2,0,"1.83","qm-pvista-slave04",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-ptiger-slave01",1,unix_timestamp());
insert into machines values (NULL,3,0,"1.83","qm-ptiger-slave02",1,unix_timestamp());
insert into machines values (NULL,4,0,"1.83","qm-pleopard-slave01",1,unix_timestamp());
insert into machines values (NULL,4,0,"1.83","qm-pleopard-slave02",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.83","qm-plinux-slave01",1,unix_timestamp());
insert into machines values (NULL,5,0,"1.83","qm-plinux-slave02",1,unix_timestamp());

-- builders
insert into machines values (NULL,6,0,NULL,"Linux_mozilla-1.9.1",1,unix_timestamp());
insert into machines values (NULL,6,0,NULL,"Linux_mozilla-1.9.1_leak_test",1,unix_timestamp());
insert into machines values (NULL,6,0,NULL,"Linux_mozilla-central",1,unix_timestamp());
insert into machines values (NULL,6,0,NULL,"Linux_mozilla-central_leak_test",1,unix_timestamp());
insert into machines values (NULL,6,0,NULL,"Linux_tracemonkey",1,unix_timestamp());
insert into machines values (NULL,7,0,NULL,"OS_X_10.5.2_mozilla-1.9.1",1,unix_timestamp());
insert into machines values (NULL,7,0,NULL,"OS_X_10.5.2_mozilla-1.9.1_leak_test",1,unix_timestamp());
insert into machines values (NULL,7,0,NULL,"OS_X_10.5.2_tracemonkey",1,unix_timestamp());
insert into machines values (NULL,7,0,NULL,"OS_X_10.5.2_mozilla-central",1,unix_timestamp());
insert into machines values (NULL,7,0,NULL,"OS_X_10.5.2_mozilla-central_leak_test",1,unix_timestamp());
insert into machines values (NULL,7,0,NULL,"OS_X_10.5.2_mozilla-central_tracemonkey",1,unix_timestamp());
insert into machines values (NULL,8,0,NULL,"WINNT_5.2_mozilla-1.9.1_leak_test",1,unix_timestamp());
insert into machines values (NULL,8,0,NULL,"WINNT_5.2_mozilla-central_leak_test",1,unix_timestamp());

insert into pagesets values (NULL,"Tp December, 2006 (393 pages)");
insert into pagesets values (NULL,"Tp November, 2000 (40 pages)");
insert into pagesets values (NULL,"DHTML");
insert into pagesets values (NULL,"GFX");
insert into pagesets values (NULL,"SVG");
insert into pagesets values (NULL,"Dromaeo");
insert into pagesets values (NULL,"SunSpider");

-- name,prettyname,ischrome,isactive,pagesetid
insert into tests values (NULL,"tp_nochrome","Tp3 NoChrome",0,1,1);
insert into tests values (NULL,"tp","Tp3",1,1,1);
insert into tests values (NULL,"tp_pbytes", "Tp3 (Private Bytes)",1,1,NULL);
insert into tests values (NULL,"tp_pbytes_nochrome","Tp3 NoChrome (Private Bytes)",0,1,NULL);
insert into tests values (NULL,"tp_rss","Tp3 (RSS)",1,1,NULL);
insert into tests values (NULL,"tp_rss_nochrome","Tp3 NoChrome (RSS)",0,1,NULL);
insert into tests values (NULL,"tp_%cpu","Tp3 (%CPU)",1,1,NULL);
insert into tests values (NULL,"tp_%cpu_nochrome","Tp3 NoChrome (%CPU)",0,1,NULL);
insert into tests values (NULL,"tp_memset","Tp3 (Memset)",1,1,NULL);
insert into tests values (NULL,"tp_memset_nochrome","Tp3 NoChrome (Memset)",0,1,NULL);
insert into tests values (NULL,"tp_fast","Tp3 Fast Cycle",1,1,2);
insert into tests values (NULL,"tp_fast_pbytes","Tp3 Fast Cycle (Private Bytes)",1,1,NULL);
insert into tests values (NULL,"tp_fast_rss","Tp3 Fast Cycle (RSS)",1,1,NULL);
insert into tests values (NULL,"tp_fast_%cpu","Tp3 Fast Cycle (%CPU)",1,1,NULL);
insert into tests values (NULL,"tp_fast_memset","Tp3 Fast Cycle (Memset)",1,1,NULL);
insert into tests values (NULL,"ts","Ts",1,1,NULL);
insert into tests values (NULL,"twinopen","Txul",1,1,NULL);
insert into tests values (NULL,"tdhtml","DHTML",1,1,3);
insert into tests values (NULL,"tdhtml_nochrome","DHTML NoChrome",0,1,3);
insert into tests values (NULL,"tgfx","GFX",1,1,4);
insert into tests values (NULL,"tgfx_nochrome","GFX NoChrome",0,1,4);
insert into tests values (NULL,"tsvg","SVG",1,1,5);
insert into tests values (NULL,"tsvg_nochrome","SVG NoChrome",0,1,5);
insert into tests values (NULL,"tjss","Dromaeo",1,1,6);
insert into tests values (NULL,"tsspider","SunSpider",1,1,7);
insert into tests values (NULL,"tsspider_nochrome","SunSpider NoChrome",0,1,7);
insert into tests values (NULL,"refcnt_leaks","Refcnt Leaks",0,1,NULL);
insert into tests values (NULL,"trace_malloc_leaks","Trace Malloc Leaks",0,1,NULL);
insert into tests values (NULL,"trace_malloc_maxheap","Trace Malloc MaxHeap",0,1,NULL);
insert into tests values (NULL,"trace_malloc_allocs","Trace Malloc Allocs",0,1,NULL);
insert into tests values (NULL,"codesighs","Codesighs",0,1,NULL);
insert into tests values (NULL,"codesighs_embed","Codesighs (embed)",0,1,NULL);
